SPB_MAXPARTYBUFFS = "Sets the number of buffs (0 to 32) displayed beneath members of your party."
SPB_MAXPARTYDEBUFFS = "Sets the number of debuffs (0 to 40) displayed beside members of your party."
SPB_FILTERDEBUFFS = "Sets the filtering of buffs and debuffs shown for members of your party by what you can cast/cure (on | off)."
SPB_CURRENT = "Currently "
SPB_PBUFFS_CHANGED = "Party buffs shown set to "
SPB_PDEBUFFS_CHANGED = "Party debuffs shown set to "
SPB_PFILTER_CHANGED = "Party buff and debuff filtering "
SPB_ENABLED = "enabled."
SPB_DISABLED = "disabled."
SPB_LOADED = "SBD::SolacePartyBuffs-".._G["SolacePartyBuffs"].version.." loaded.  Type /solace for help."
SPB_NATURES_CURE = "Nature's Cure"
SPB_IMP_CLEANSE_SPI = "Improved Cleanse Spirit"
SPB_SACRED_CLEANSING = "Sacred Cleansing"

if ( GetLocale() == "zhTW" ) then
	SPB_MAXPARTYBUFFS = "設定隊友可顯示的BUFF數量. ( 0-32 )."
	SPB_MAXPARTYDEBUFFS = "設定隊友可顯示的DEBUFF數量. ( 0-40 )."
	SPB_FILTERDEBUFFS = "設定是否過濾隊友的BUFF/DEBUFF (on | off)."
	SPB_CURRENT = "目前 "
	SPB_PBUFFS_CHANGED = "隊友可顯示的BUFF數量設定為 "
	SPB_PDEBUFFS_CHANGED = "隊友可顯示的DEBUFF數量設定為 "
	SPB_PFILTER_CHANGED = "隊友的BUFF/DEBUFF過濾 "
	SPB_ENABLED = "啟用."
	SPB_DISABLED = "關閉."
	SPB_LOADED = "SBD::SolacePartyBuffs-"..SPB_VER.." 已載入.  輸入 /solace 顯示說明."
end
